package com.bku.pojos;
// Generated Nov 6, 2018 11:13:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ManagementSekolah generated by hbm2java
 */
public class ManagementSekolah  implements java.io.Serializable {


     private long id;
     private String alamatRumahKepalaSekolah;
     private String namaBendahara;
     private String namaKepalaSekolah;
     private String namaKepalaUptDisdikbud;
     private String namaKetuaKomiteSekolah;
     private String namaKetuaTimBosKabupaten;
     private String nipBendahara;
     private String nipKepalaSekolah;
     private String nipKepalaUptDisdikbud;
     private String nipKetuaTimBosKabupaten;
     private String nomorSkBendaharaBos;
     private String nomorSkKepalaSekolah;
     private Date tanggalSkBendaharaBos;
     private Date tanggalSkKepalaSekolah;
     private Set<Sekolah> sekolahs = new HashSet<Sekolah>(0);

    public ManagementSekolah() {
    }

	
    public ManagementSekolah(long id) {
        this.id = id;
    }
    public ManagementSekolah(long id, String alamatRumahKepalaSekolah, String namaBendahara, String namaKepalaSekolah, String namaKepalaUptDisdikbud, String namaKetuaKomiteSekolah, String namaKetuaTimBosKabupaten, String nipBendahara, String nipKepalaSekolah, String nipKepalaUptDisdikbud, String nipKetuaTimBosKabupaten, String nomorSkBendaharaBos, String nomorSkKepalaSekolah, Date tanggalSkBendaharaBos, Date tanggalSkKepalaSekolah, Set<Sekolah> sekolahs) {
       this.id = id;
       this.alamatRumahKepalaSekolah = alamatRumahKepalaSekolah;
       this.namaBendahara = namaBendahara;
       this.namaKepalaSekolah = namaKepalaSekolah;
       this.namaKepalaUptDisdikbud = namaKepalaUptDisdikbud;
       this.namaKetuaKomiteSekolah = namaKetuaKomiteSekolah;
       this.namaKetuaTimBosKabupaten = namaKetuaTimBosKabupaten;
       this.nipBendahara = nipBendahara;
       this.nipKepalaSekolah = nipKepalaSekolah;
       this.nipKepalaUptDisdikbud = nipKepalaUptDisdikbud;
       this.nipKetuaTimBosKabupaten = nipKetuaTimBosKabupaten;
       this.nomorSkBendaharaBos = nomorSkBendaharaBos;
       this.nomorSkKepalaSekolah = nomorSkKepalaSekolah;
       this.tanggalSkBendaharaBos = tanggalSkBendaharaBos;
       this.tanggalSkKepalaSekolah = tanggalSkKepalaSekolah;
       this.sekolahs = sekolahs;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getAlamatRumahKepalaSekolah() {
        return this.alamatRumahKepalaSekolah;
    }
    
    public void setAlamatRumahKepalaSekolah(String alamatRumahKepalaSekolah) {
        this.alamatRumahKepalaSekolah = alamatRumahKepalaSekolah;
    }
    public String getNamaBendahara() {
        return this.namaBendahara;
    }
    
    public void setNamaBendahara(String namaBendahara) {
        this.namaBendahara = namaBendahara;
    }
    public String getNamaKepalaSekolah() {
        return this.namaKepalaSekolah;
    }
    
    public void setNamaKepalaSekolah(String namaKepalaSekolah) {
        this.namaKepalaSekolah = namaKepalaSekolah;
    }
    public String getNamaKepalaUptDisdikbud() {
        return this.namaKepalaUptDisdikbud;
    }
    
    public void setNamaKepalaUptDisdikbud(String namaKepalaUptDisdikbud) {
        this.namaKepalaUptDisdikbud = namaKepalaUptDisdikbud;
    }
    public String getNamaKetuaKomiteSekolah() {
        return this.namaKetuaKomiteSekolah;
    }
    
    public void setNamaKetuaKomiteSekolah(String namaKetuaKomiteSekolah) {
        this.namaKetuaKomiteSekolah = namaKetuaKomiteSekolah;
    }
    public String getNamaKetuaTimBosKabupaten() {
        return this.namaKetuaTimBosKabupaten;
    }
    
    public void setNamaKetuaTimBosKabupaten(String namaKetuaTimBosKabupaten) {
        this.namaKetuaTimBosKabupaten = namaKetuaTimBosKabupaten;
    }
    public String getNipBendahara() {
        return this.nipBendahara;
    }
    
    public void setNipBendahara(String nipBendahara) {
        this.nipBendahara = nipBendahara;
    }
    public String getNipKepalaSekolah() {
        return this.nipKepalaSekolah;
    }
    
    public void setNipKepalaSekolah(String nipKepalaSekolah) {
        this.nipKepalaSekolah = nipKepalaSekolah;
    }
    public String getNipKepalaUptDisdikbud() {
        return this.nipKepalaUptDisdikbud;
    }
    
    public void setNipKepalaUptDisdikbud(String nipKepalaUptDisdikbud) {
        this.nipKepalaUptDisdikbud = nipKepalaUptDisdikbud;
    }
    public String getNipKetuaTimBosKabupaten() {
        return this.nipKetuaTimBosKabupaten;
    }
    
    public void setNipKetuaTimBosKabupaten(String nipKetuaTimBosKabupaten) {
        this.nipKetuaTimBosKabupaten = nipKetuaTimBosKabupaten;
    }
    public String getNomorSkBendaharaBos() {
        return this.nomorSkBendaharaBos;
    }
    
    public void setNomorSkBendaharaBos(String nomorSkBendaharaBos) {
        this.nomorSkBendaharaBos = nomorSkBendaharaBos;
    }
    public String getNomorSkKepalaSekolah() {
        return this.nomorSkKepalaSekolah;
    }
    
    public void setNomorSkKepalaSekolah(String nomorSkKepalaSekolah) {
        this.nomorSkKepalaSekolah = nomorSkKepalaSekolah;
    }
    public Date getTanggalSkBendaharaBos() {
        return this.tanggalSkBendaharaBos;
    }
    
    public void setTanggalSkBendaharaBos(Date tanggalSkBendaharaBos) {
        this.tanggalSkBendaharaBos = tanggalSkBendaharaBos;
    }
    public Date getTanggalSkKepalaSekolah() {
        return this.tanggalSkKepalaSekolah;
    }
    
    public void setTanggalSkKepalaSekolah(Date tanggalSkKepalaSekolah) {
        this.tanggalSkKepalaSekolah = tanggalSkKepalaSekolah;
    }
    public Set<Sekolah> getSekolahs() {
        return this.sekolahs;
    }
    
    public void setSekolahs(Set<Sekolah> sekolahs) {
        this.sekolahs = sekolahs;
    }




}


