package com.bku.pojos;
// Generated Nov 6, 2018 11:13:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sekolah generated by hbm2java
 */
public class Sekolah  implements java.io.Serializable,Comparable<Sekolah> {


     private long npsn;
     private ManagementSekolah managementSekolah;
     private Date createdAt;
     private Date updatedAt;
     private Long createdBy;
     private Long updatedBy;
     private String alamat;
     private String desaKelurahan;
     private String dusun;
     private String email;
     private String kabupatenKota;
     private String kecamatan;
     private String kodePos;
     private String namaBank;
     private String namaSekolah;
     private String noRekening;
     private String npwp;
     private String nss;
     private String provinsi;
     private String rt;
     private String rw;
     private Set<Bku2022> bku2022s = new HashSet<Bku2022>(0);
     private Set<Bku2025> bku2025s = new HashSet<Bku2025>(0);
     private Set<Bku2021> bku2021s = new HashSet<Bku2021>(0);
     private Set<Bku2019> bku2019s = new HashSet<Bku2019>(0);
     private Set<Bku2023> bku2023s = new HashSet<Bku2023>(0);
     private Set<Bku2027> bku2027s = new HashSet<Bku2027>(0);
     private Set<Bku2026> bku2026s = new HashSet<Bku2026>(0);
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<Bku2018> bku2018s = new HashSet<Bku2018>(0);
     private Set<Bku2020> bku2020s = new HashSet<Bku2020>(0);
     private Set<Bku2028> bku2028s = new HashSet<Bku2028>(0);
     private Set<Bku2024> bku2024s = new HashSet<Bku2024>(0);

    public Sekolah() {
    }

	
    public Sekolah(long npsn) {
        this.npsn = npsn;
    }
    public Sekolah(long npsn, ManagementSekolah managementSekolah, Date createdAt, Date updatedAt, Long createdBy, Long updatedBy, String alamat, String desaKelurahan, String dusun, String email, String kabupatenKota, String kecamatan, String kodePos, String namaBank, String namaSekolah, String noRekening, String npwp, String nss, String provinsi, String rt, String rw, Set<Bku2022> bku2022s, Set<Bku2025> bku2025s, Set<Bku2021> bku2021s, Set<Bku2019> bku2019s, Set<Bku2023> bku2023s, Set<Bku2027> bku2027s, Set<Bku2026> bku2026s, Set<Users> userses, Set<Bku2018> bku2018s, Set<Bku2020> bku2020s, Set<Bku2028> bku2028s, Set<Bku2024> bku2024s) {
       this.npsn = npsn;
       this.managementSekolah = managementSekolah;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.alamat = alamat;
       this.desaKelurahan = desaKelurahan;
       this.dusun = dusun;
       this.email = email;
       this.kabupatenKota = kabupatenKota;
       this.kecamatan = kecamatan;
       this.kodePos = kodePos;
       this.namaBank = namaBank;
       this.namaSekolah = namaSekolah;
       this.noRekening = noRekening;
       this.npwp = npwp;
       this.nss = nss;
       this.provinsi = provinsi;
       this.rt = rt;
       this.rw = rw;
       this.bku2022s = bku2022s;
       this.bku2025s = bku2025s;
       this.bku2021s = bku2021s;
       this.bku2019s = bku2019s;
       this.bku2023s = bku2023s;
       this.bku2027s = bku2027s;
       this.bku2026s = bku2026s;
       this.userses = userses;
       this.bku2018s = bku2018s;
       this.bku2020s = bku2020s;
       this.bku2028s = bku2028s;
       this.bku2024s = bku2024s;
    }
   
    public long getNpsn() {
        return this.npsn;
    }
    
    public void setNpsn(long npsn) {
        this.npsn = npsn;
    }
    public ManagementSekolah getManagementSekolah() {
        return this.managementSekolah;
    }
    
    public void setManagementSekolah(ManagementSekolah managementSekolah) {
        this.managementSekolah = managementSekolah;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Long getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getDesaKelurahan() {
        return this.desaKelurahan;
    }
    
    public void setDesaKelurahan(String desaKelurahan) {
        this.desaKelurahan = desaKelurahan;
    }
    public String getDusun() {
        return this.dusun;
    }
    
    public void setDusun(String dusun) {
        this.dusun = dusun;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getKabupatenKota() {
        return this.kabupatenKota;
    }
    
    public void setKabupatenKota(String kabupatenKota) {
        this.kabupatenKota = kabupatenKota;
    }
    public String getKecamatan() {
        return this.kecamatan;
    }
    
    public void setKecamatan(String kecamatan) {
        this.kecamatan = kecamatan;
    }
    public String getKodePos() {
        return this.kodePos;
    }
    
    public void setKodePos(String kodePos) {
        this.kodePos = kodePos;
    }
    public String getNamaBank() {
        return this.namaBank;
    }
    
    public void setNamaBank(String namaBank) {
        this.namaBank = namaBank;
    }
    public String getNamaSekolah() {
        return this.namaSekolah;
    }
    
    public void setNamaSekolah(String namaSekolah) {
        this.namaSekolah = namaSekolah;
    }
    public String getNoRekening() {
        return this.noRekening;
    }
    
    public void setNoRekening(String noRekening) {
        this.noRekening = noRekening;
    }
    public String getNpwp() {
        return this.npwp;
    }
    
    public void setNpwp(String npwp) {
        this.npwp = npwp;
    }
    public String getNss() {
        return this.nss;
    }
    
    public void setNss(String nss) {
        this.nss = nss;
    }
    public String getProvinsi() {
        return this.provinsi;
    }
    
    public void setProvinsi(String provinsi) {
        this.provinsi = provinsi;
    }
    public String getRt() {
        return this.rt;
    }
    
    public void setRt(String rt) {
        this.rt = rt;
    }
    public String getRw() {
        return this.rw;
    }
    
    public void setRw(String rw) {
        this.rw = rw;
    }
    public Set<Bku2022> getBku2022s() {
        return this.bku2022s;
    }
    
    public void setBku2022s(Set<Bku2022> bku2022s) {
        this.bku2022s = bku2022s;
    }
    public Set<Bku2025> getBku2025s() {
        return this.bku2025s;
    }
    
    public void setBku2025s(Set<Bku2025> bku2025s) {
        this.bku2025s = bku2025s;
    }
    public Set<Bku2021> getBku2021s() {
        return this.bku2021s;
    }
    
    public void setBku2021s(Set<Bku2021> bku2021s) {
        this.bku2021s = bku2021s;
    }
    public Set<Bku2019> getBku2019s() {
        return this.bku2019s;
    }
    
    public void setBku2019s(Set<Bku2019> bku2019s) {
        this.bku2019s = bku2019s;
    }
    public Set<Bku2023> getBku2023s() {
        return this.bku2023s;
    }
    
    public void setBku2023s(Set<Bku2023> bku2023s) {
        this.bku2023s = bku2023s;
    }
    public Set<Bku2027> getBku2027s() {
        return this.bku2027s;
    }
    
    public void setBku2027s(Set<Bku2027> bku2027s) {
        this.bku2027s = bku2027s;
    }
    public Set<Bku2026> getBku2026s() {
        return this.bku2026s;
    }
    
    public void setBku2026s(Set<Bku2026> bku2026s) {
        this.bku2026s = bku2026s;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
    public Set<Bku2018> getBku2018s() {
        return this.bku2018s;
    }
    
    public void setBku2018s(Set<Bku2018> bku2018s) {
        this.bku2018s = bku2018s;
    }
    public Set<Bku2020> getBku2020s() {
        return this.bku2020s;
    }
    
    public void setBku2020s(Set<Bku2020> bku2020s) {
        this.bku2020s = bku2020s;
    }
    public Set<Bku2028> getBku2028s() {
        return this.bku2028s;
    }
    
    public void setBku2028s(Set<Bku2028> bku2028s) {
        this.bku2028s = bku2028s;
    }
    public Set<Bku2024> getBku2024s() {
        return this.bku2024s;
    }
    
    public void setBku2024s(Set<Bku2024> bku2024s) {
        this.bku2024s = bku2024s;
    }

    @Override
    public int compareTo(Sekolah o) {
        return (int)(npsn - o.getNpsn());
    }




}


