package com.bku.pojos;
// Generated Nov 6, 2018 11:13:09 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StandarAkreditasi generated by hbm2java
 */
public class StandarAkreditasi  implements java.io.Serializable {


     private long id;
     private Date createdAt;
     private Date updatedAt;
     private Long createdBy;
     private Long updatedBy;
     private String kode;
     private String uraian;

    public StandarAkreditasi() {
    }

	
    public StandarAkreditasi(long id) {
        this.id = id;
    }
    public StandarAkreditasi(long id, Date createdAt, Date updatedAt, Long createdBy, Long updatedBy, String kode, String uraian) {
       this.id = id;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.kode = kode;
       this.uraian = uraian;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Long getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
    public String getKode() {
        return this.kode;
    }
    
    public void setKode(String kode) {
        this.kode = kode;
    }
    public String getUraian() {
        return this.uraian;
    }
    
    public void setUraian(String uraian) {
        this.uraian = uraian;
    }




}


