package com.bku.pojos;
// Generated Nov 6, 2018 11:13:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long id;
     private Sekolah sekolah;
     private Date createdAt;
     private Date updatedAt;
     private String email;
     private String name;
     private String password;
     private String tahunAktif;
     private String username;
     private Set<Roles> roleses = new HashSet<Roles>(0);

    public Users() {
    }

	
    public Users(long id) {
        this.id = id;
    }
    public Users(long id, Sekolah sekolah, Date createdAt, Date updatedAt, String email, String name, String password, String tahunAktif, String username, Set<Roles> roleses) {
       this.id = id;
       this.sekolah = sekolah;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.email = email;
       this.name = name;
       this.password = password;
       this.tahunAktif = tahunAktif;
       this.username = username;
       this.roleses = roleses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Sekolah getSekolah() {
        return this.sekolah;
    }
    
    public void setSekolah(Sekolah sekolah) {
        this.sekolah = sekolah;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTahunAktif() {
        return this.tahunAktif;
    }
    
    public void setTahunAktif(String tahunAktif) {
        this.tahunAktif = tahunAktif;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }




}


